import { Choice, NavButtons } from '../components/forms/FormControls'
import type { AssessmentState } from '../types/assessment'

const cvdOptions = [['cad','โรคหลอดเลือดหัวใจ'],['mi','กล้ามเนื้อหัวใจขาดเลือด/หัวใจวาย'],['pci','เคยทำ PCI หรือใส่ขดลวดหลอดเลือดหัวใจ'],['cabg','เคยผ่าตัดหลอดเลือดหัวใจ CABG'],['stroke','โรคหลอดเลือดสมอง หรือ TIA'],['pad','โรคหลอดเลือดแดงส่วนปลาย'],['none','ไม่มีประวัติข้างต้น']]
const symptomOptions = [['chest_pain','เจ็บหรือแน่นหน้าอก'],['breathlessness','หายใจลำบากเฉียบพลัน'],['syncope','หมดสติ / ใกล้หมดสติ'],['weakness','แขนหรือขาอ่อนแรงเฉียบพลัน'],['face_droop','ปากเบี้ย'],['speech','พูดไม่ชัด'],['severe','อาการผิดปกติรุนแรงที่เกิดขึ้นทันที'],['none','ไม่มีอาการดังกล่าว']]

export function EligibilityPage({ data, toggleList, errors, onBack, onNext }: { data: AssessmentState; toggleList: (key: 'existingCvd'|'redFlags', value: string, noneValue: string) => void; errors: Record<string,string>; onBack: () => void; onNext: () => void }) {
  return <section className="page-wrap-wide"><div className="eyebrow">2 · ประวัติสุขภาพ</div><h1 className="page-title">ตรวจความเหมาะสมและความปลอดภัย</h1><p className="page-lead">ตอบตามที่ทราบ แบบประเมินจะเลือกเส้นทางที่ปลอดภัยที่สุดจากคำตอบของคุณ</p><div className="mt-8 grid gap-8 lg:grid-cols-2"><fieldset><legend className="mb-4 text-base font-bold">เคยได้รับการวินิจฉัยหรือรักษาโรคเหล่านี้หรือไม่?</legend><div className="space-y-2" role="radiogroup">{cvdOptions.map(([id,label]) => <Choice key={id} selected={data.existingCvd.includes(id)} title={label} onClick={() => toggleList('existingCvd', id, 'none')} />)}</div>{errors.existingCvd ? <p role="alert" className="mt-2 text-sm text-red-700">{errors.existingCvd}</p> : null}</fieldset><fieldset><legend className="mb-4 text-base font-bold">ขณะนี้คุณมีอาการเหล่านี้หรือไม่?</legend><div className="space-y-2" role="radiogroup">{symptomOptions.map(([id,label]) => <Choice key={id} selected={data.redFlags.includes(id)} title={label} danger={id !== 'none'} onClick={() => toggleList('redFlags', id, 'none')} />)}</div>{errors.redFlags ? <p role="alert" className="mt-2 text-sm text-red-700">{errors.redFlags}</p> : null}</fieldset></div><NavButtons onBack={onBack} onNext={onNext} /></section>
}
