import { ArrowRight, Clock3, HeartHandshake, ShieldCheck, Sparkles } from 'lucide-react'
import { trackEvent } from '../services/analytics'

export function LandingPage({ onStart }: { onStart: () => void }) {
  const start = () => { trackEvent('cv_assessment_start'); onStart() }
  return <section className="mx-auto grid max-w-6xl gap-12 px-4 pb-16 pt-10 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pt-20">
    <div><span className="inline-flex items-center gap-2 rounded-full border border-sage-200 bg-white/80 px-3 py-2 text-xs font-semibold text-sage-700"><Sparkles size={15} /> เข้าใจสุขภาพหัวใจของคุณได้ง่ายขึ้น</span><h1 className="mt-6 max-w-3xl text-4xl font-bold leading-[1.14] tracking-tight text-ink sm:text-5xl lg:text-[58px]">ประเมินความเสี่ยงโรคหัวใจและหลอดเลือดใน 10 ปี</h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">รู้ระดับความเสี่ยงของคุณภายในไม่กี่นาที พร้อมรับคำแนะนำการดูแลสุขภาพและโปรแกรมตรวจที่เหมาะกับคุณ</p><button type="button" onClick={start} className="mt-8 inline-flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-ink px-7 font-semibold text-white shadow-xl shadow-sage-900/15 transition hover:-translate-y-0.5 hover:bg-sage-700 sm:w-auto">เริ่มประเมินความเสี่ยง <ArrowRight size={19} /></button><p className="mt-3 flex items-center justify-center gap-2 text-xs text-slate-500 sm:justify-start"><Clock3 size={15} /> ใช้เวลาประมาณ 2–3 นาที</p></div>
    <div className="relative"><div className="absolute -inset-5 -z-10 rounded-[40px] bg-gradient-to-br from-sage-100 to-transparent blur-xl" /><div className="rounded-[28px] border border-white bg-white/85 p-5 shadow-card backdrop-blur sm:p-7"><div className="rounded-2xl bg-ink p-6 text-white"><p className="text-sm text-sage-200">ภาพรวมการประเมิน</p><p className="mt-2 text-3xl font-bold">เฉพาะคุณ เข้าใจง่าย</p><div className="mt-8 flex items-end gap-2" aria-hidden="true">{[30,45,38,60,54,78,68,90].map((h, i) => <span key={i} className="flex-1 rounded-t-md bg-sage-500/70" style={{ height: `${h}px` }} />)}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{[[ShieldCheck,'ประเมินเฉพาะบุคคล'],[HeartHandshake,'ใช้ข้อมูลพื้นฐาน'],[Sparkles,'รับคำแนะนำทันที']].map(([Icon,label]) => { const I = Icon as typeof ShieldCheck; return <div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-4"><span className="grid size-10 place-items-center rounded-xl bg-sage-50 text-sage-700"><I size={20}/></span><span className="text-sm font-semibold">{String(label)}</span></div>})}</div></div></div>
  </section>
}
