import { AlertTriangle, ArrowRight, CheckCircle2, HeartPulse, PhoneCall, ShieldAlert, Stethoscope } from 'lucide-react'
import { RiskRing } from '../components/result/RiskRing'
import type { AssessmentState, LeadIntent, RiskResult } from '../types/assessment'
import type { PackageMatch } from '../types/package'
import type { RecommendationResult, RiskFactor } from '../types/recommendation'

const riskLabel = { low: 'ความเสี่ยงต่ำ', intermediate: 'ความเสี่ยงปานกลาง', high: 'ความเสี่ยงสูง' }

interface Props { data: AssessmentState; result: RiskResult | null; age: number; factors: RiskFactor[]; recommendations: RecommendationResult; packages: PackageMatch[]; saveError: string; onBack: () => void; onPackage: (id: string) => void; onIntent: (intent: LeadIntent) => void; onMarketingConsent: (value: boolean) => void; onSubmit: () => void; busy: boolean }

export function ResultPage({ data, result, age, factors, recommendations, packages, saveError, onBack, onPackage, onIntent, onMarketingConsent, onSubmit, busy }: Props) {
  const emergency = data.redFlags.some((item) => item !== 'none'); const established = data.existingCvd.some((item) => item !== 'none')
  if (emergency) return <section className="page-wrap"><div className="rounded-[28px] border-2 border-red-200 bg-red-50 p-6 sm:p-8"><ShieldAlert className="text-red-700" size={34}/><h1 className="mt-4 text-2xl font-bold text-red-950">อาการที่คุณระบุอาจต้องได้รับการประเมินทางการแพทย์โดยเร็ว</h1><p className="mt-3 leading-7 text-red-900">ไม่ควรรอผลจากแบบประเมินออนไลน์ หากอาการกำลังเป็นอยู่ รุนแรง หรือแย่ลง ให้ติดต่อบริการการแพทย์ฉุกเฉินทันที</p><a href={`tel:${import.meta.env.VITE_EMERGENCY_PHONE || '056-000111'}`} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-red-700 px-5 font-semibold text-white sm:w-auto"><PhoneCall size={19}/> โทร {import.meta.env.VITE_EMERGENCY_PHONE || '056-000111'}</a><p className="mt-3 text-xs text-red-800">หากไม่สามารถติดต่อโรงพยาบาลได้ ให้โทร 1669</p></div><p className="mt-5 text-sm leading-6 text-slate-500">ระบบหยุดการคำนวณและไม่แสดงโปรแกรมตรวจเป็นคำแนะนำหลักเพื่อความปลอดภัย</p><button type="button" onClick={onBack} className="mt-7 min-h-11 font-semibold text-slate-600">ย้อนกลับไปแก้ข้อมูล</button></section>
  if (established) return <section className="page-wrap"><div className="eyebrow"><Stethoscope size={16}/> เส้นทางดูแลเฉพาะบุคคล</div><h1 className="page-title">แนะนำให้พบแพทย์เพื่อประเมินโดยตรง</h1><p className="page-lead">เนื่องจากคุณมีประวัติโรคหัวใจหรือหลอดเลือดอยู่แล้ว การใช้แบบประเมินสำหรับผู้ที่ยังไม่เคยเกิดโรคอาจไม่เหมาะสม เราจึงไม่แสดง Thai CV Risk % เป็นผลหลัก</p><div className="mt-8 rounded-2xl border border-sage-200 bg-sage-50 p-5"><h2 className="font-bold">ขั้นตอนที่เหมาะสมกว่า</h2><p className="mt-2 text-sm leading-6 text-slate-600">ทบทวนประวัติ ยา ผลตรวจเดิม และแผนการดูแลกับแพทย์ ไม่ควรปรับยาหรือการรักษาจากผลออนไลน์</p></div><IntentPanel data={data} onIntent={onIntent} onMarketingConsent={onMarketingConsent} onSubmit={onSubmit} busy={busy} saveError={saveError} physicianFirst /></section>
  if (!result) return null
  return <section className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div className="rounded-[30px] border border-white bg-white p-6 shadow-card sm:p-9"><div className="grid items-center gap-7 sm:grid-cols-[200px_1fr]"><RiskRing risk={result.riskPercent} level={result.riskLevel}/><div><span className="text-sm font-semibold text-sage-700">ผลประเมินของคุณ · อายุ {age} ปี</span><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">ความเสี่ยงโรคหัวใจและหลอดเลือดใน 10 ปี</h1><span className="mt-4 inline-flex rounded-full border border-sage-200 bg-sage-50 px-3 py-1.5 text-sm font-bold">{riskLabel[result.riskLevel]}</span><p className="mt-4 text-sm leading-6 text-slate-600">หมายถึงจากคน 100 คนที่มีข้อมูลใกล้เคียงกับคุณ อาจมีประมาณ {Math.round(result.riskPercent)} คนเกิดโรคหัวใจหรือหลอดเลือดภายใน 10 ปี ผลนี้ไม่ได้ทำนายว่าจะเกิดกับคุณแน่นอน</p></div></div></div>
  <div className="mt-7 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="result-section"><h2 className="section-title"><HeartPulse/> ปัจจัยที่ควรให้ความสำคัญ</h2><div className="mt-4 space-y-3">{factors.map((factor) => <div key={factor.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold">{factor.label}</p><p className="mt-1 text-sm leading-6 text-slate-600">{factor.detail}</p></div>)}</div></section><section className="result-section"><h2 className="section-title"><CheckCircle2/> คำแนะนำที่เหมาะกับข้อมูลของคุณ</h2><div className="mt-4 space-y-4">{recommendations.clinicalRecommendations.map((item) => <article key={item.id}><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{item.description}</p><p className="mt-1 text-xs text-sage-700">เหตุผล: {item.reason}</p></article>)}{recommendations.lifestyleRecommendations.map((item) => <article key={item.id}><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{item.description}</p></article>)}{!recommendations.clinicalRecommendations.length && !recommendations.lifestyleRecommendations.length ? <p className="rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">ยังโหลดคำแนะนำที่ผ่านการอนุมัติไม่ได้ จึงไม่แสดงคำแนะนำหรือโปรแกรมแบบคาดเดา กรุณาลองใหม่ภายหลัง</p> : null}</div></section></div>
  {packages.length ? <section className="mt-7"><div className="mb-4"><p className="eyebrow">บริการของโรงพยาบาล · ทางเลือก</p><h2 className="text-2xl font-bold">โปรแกรมตรวจสุขภาพที่โรงพยาบาลมีให้เลือก</h2><p className="mt-2 text-sm text-slate-600">รายการทั้งหมดที่เปิดใช้งาน คุณสามารถเลือกโปรแกรมที่สนใจได้ โดยควรปรึกษาบุคลากรทางการแพทย์ก่อนตัดสินใจ</p></div><div className="grid gap-4 md:grid-cols-2">{packages.map((pkg) => <article key={pkg.packageId} className={`overflow-hidden rounded-3xl border bg-white shadow-card ${data.selectedPackageId === pkg.packageId ? 'border-sage-600 ring-4 ring-sage-100' : 'border-slate-100'}`}>{pkg.imageUrl ? <img src={pkg.imageUrl} alt={pkg.packageName} className="aspect-[16/9] w-full object-cover" loading="lazy" /> : null}<div className="p-5"><div className="flex justify-between gap-3"><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-bold text-amber-800">DEMO ONLY</span><span className="text-xs text-slate-400">{pkg.packageId}</span></div><h3 className="mt-4 text-lg font-bold">{pkg.packageName}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{pkg.shortDescription}</p><button type="button" onClick={() => onPackage(pkg.packageId)} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-ink font-semibold text-ink hover:bg-sage-50">{data.selectedPackageId === pkg.packageId ? 'เลือกแล้ว' : 'สนใจโปรแกรมนี้'} <ArrowRight size={16}/></button></div></article>)}</div></section> : null}
  <IntentPanel data={data} onIntent={onIntent} onMarketingConsent={onMarketingConsent} onSubmit={onSubmit} busy={busy} saveError={saveError} />
  <div className="mt-7 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><AlertTriangle className="mt-0.5 shrink-0" size={19}/><p>ผลนี้เป็นการประมาณจากข้อมูลที่คุณกรอกและไม่ใช่การวินิจฉัย การประเมินจริงอาจแตกต่างตามประวัติสุขภาพ ผลตรวจ และปัจจัยอื่น ควรปรึกษาแพทย์เมื่อมีข้อสงสัยหรือมีปัจจัยเสี่ยงสูง</p></div>
  {import.meta.env.DEV ? <details className="mt-5 rounded-xl bg-slate-950 p-4 text-xs text-slate-200"><summary className="cursor-pointer font-semibold">Development calculation audit</summary><pre className="mt-3 overflow-x-auto">{JSON.stringify({ model: result.modelType, fullScore: result.fullScore, riskPercent: result.riskPercent, riskLevel: result.riskLevel, matchedRules: recommendations.matchedRuleIds, packageTags: recommendations.packageTags }, null, 2)}</pre></details> : null}</section>
}

function IntentPanel({ data, onIntent, onMarketingConsent, onSubmit, busy, saveError, physicianFirst = false }: { data: AssessmentState; onIntent: (intent: LeadIntent) => void; onMarketingConsent: (value: boolean) => void; onSubmit: () => void; busy: boolean; saveError: string; physicianFirst?: boolean }) {
  const options: [LeadIntent,string][] = physicianFirst ? [['doctor_appointment','ต้องการนัดพบแพทย์'],['callback','ให้เจ้าหน้าที่ติดต่อกลับ'],['none','ยังไม่ต้องการให้ติดต่อ']] : [['callback','ให้เจ้าหน้าที่ติดต่อกลับ'],['package_interest','สนใจโปรแกรมที่เลือก'],['doctor_appointment','ต้องการนัดพบแพทย์'],['none','ยังไม่ต้องการให้ติดต่อ']]
  const needsConsent = Boolean(data.leadIntent && data.leadIntent !== 'none')
  return <section className="mt-7 rounded-3xl bg-ink p-5 text-white sm:p-7"><h2 className="text-xl font-bold">ต้องการให้เราช่วยอะไรต่อ?</h2><p className="mt-1 text-sm text-sage-200">ไม่ต้องกรอกชื่อหรือเบอร์โทรซ้ำ</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{options.map(([id,label]) => <button type="button" key={id} onClick={() => onIntent(id)} className={`min-h-12 rounded-xl border px-4 text-left text-sm font-semibold transition ${data.leadIntent === id ? 'border-white bg-white text-ink' : 'border-white/20 hover:bg-white/10'}`}>{label}</button>)}</div>{needsConsent && !data.consentMarketing ? <label className="mt-4 flex cursor-pointer gap-3 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-950"><input type="checkbox" className="mt-0.5 size-5 shrink-0 accent-[#315e4c]" checked={data.consentMarketing} onChange={(e) => onMarketingConsent(e.target.checked)} /><span>ข้าพเจ้ายินยอมให้โรงพยาบาลติดต่อกลับตามวัตถุประสงค์ที่เลือกในครั้งนี้</span></label> : null}{saveError ? <p role="alert" className="mt-4 text-sm font-semibold text-amber-200">{saveError}</p> : null}<button type="button" disabled={!data.leadIntent || busy || (needsConsent && !data.consentMarketing)} onClick={onSubmit} className="mt-5 min-h-12 w-full rounded-xl bg-white px-5 font-bold text-ink disabled:opacity-50">{busy ? 'กำลังบันทึก…' : data.leadIntent === 'none' ? 'เสร็จสิ้นการประเมิน' : 'ส่งคำขอ'}</button></section>
}
